### ISSUE TITLE
Parameter Assertion Syntax

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#10]
The syntax for asserting rule parameters into a node is a bit cumbersome (at least for me). By this I mean the `"'&p'"` in the `:assert` clause of the node definition.

```
(rule 'foo ['p]
      :read (pattern (node 'parent :label GOAL :asserts {:id "'&p'"}))
```

I often find my self skipping one of inner quotes or forgetting the `&`.

Can this be shortened to just the symbol, e.g., `'p`?

**Comment by jenshweber** [comment]
Maybe I should explain this construction better. 
* **double quotes**: Parameter values are always passed as Strings to Grape rules. This is to allow Grape users to perform more complex computation, for example accessing the parameters of other nodes in the context of the rule match. For example, if you wanted to assert a price property for a node based on the price of another node, plus a price difference _p_, which is passed as a parameter, you could write the following expression in the string: `` "n1.price+&p"``

* **single quotes**: These quotes are not always necessary. You only need them if you want to use Strings as the data type for the node attribute. If you are using a number data type as an ID in your above example, you can write the rule like this:

```
(rule 'foo ['p]
      :read (pattern (node 'parent :label GOAL :asserts {:id "&p"}))
```

The & symbol is used to let Grape know that it should replace this part of the string with the value of the parameter. (This is akin to other embedded DSLs, for example embedded SQL. In SQL, you would for example use a colon (:) do denote a parameter, like so:

``String sql = "select count(*) from T_ACTOR where first_name = :first_name";``

**Suggestion:**

So, we can't really get rid of the double quotes and the ampersand (or a similar special character). We _could_ get rid of the need to use the _inner quotes_ for String data types by having grape to automatically check the data type of the parameter that was passed to the rule (p in the above case) and, if it is a string, it could automatically generate the inner quotes.

Does that make sense? Any other thoughts?

**Comment by sdiemert** [comment]
@jenshweber - that really helps. Now that I understand how this construct works, I agree, it doesn't need to be changed. Closing the issue.

**Comment by jenshweber** [comment]
@sdiemert What do you think about the suggestion of automatically detecting a string data type and quoting it? Do we want that? Is it worth the effort? It _can_ be done - but I am not sure if it's worth the effort.

**Comment by sdiemert** [comment]
@jenshweber - Agreed, not worth the effort.

Quote of strings is actually nice because it forces you to consider whether something is a string or not. So I like this. Previously, I had assumed everything was a string, so it didn't quite make sense to me to have the single quotes, but since you can have non-string data in the assert clauses, it makes sense to include quotes.
