### ISSUE TITLE
Optional Matches in Rules

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#11]
It would be helpful to have optional matches in rules. By this I mean a node/edge that is not required for rule application, but if it is matched, then it can be operated on. 

For example: 

```clojure
(rule 'fire-worker ['name]
    :read (pattern 
                 (node 'w :label "Worker" :asserts {:name 'name})
                 (node 'c :label "Company")
                 (node 'd :label "Department" :optional)
                 (edge 'e1 :label "employer" :src 'w :tar 'c)
                 (edge 'e2 :label "in_dept" :src 'w :tar 'd)
    :delete ['e1 'e2])
```

Notice that `'e2` is also optional, because of the optional existence of `'d`. 

At the moment (I think) this delete operation would have to be expanded as two rules, one where the worker is in a department and another where they are not. Using optional matches would make GT specifications more concise.

**Comment by jenshweber** [comment]
I agree that this would make specifications more precise. I did a bit of experimentation. I believe this is achievable without too many changes. I am looking into this.

**Comment by jenshweber** [comment]
@sdiemert Wow, that was quite a bit more challenging than I originally thought. 

I believe I have it done now. (Version 0.2.5)

Please note: you have to add the following line to your neo4j.conf file:
``` cypher.lenient_create_relationship=true ```
(and restart neo4j of course)

I will have to update the VM as well.

Given that we have optional nodes/edges now, I changed the visual representation to use dashed edges to indicate optionaiity (instead of NACs)

The tutorial is updated.

Note: this is not heavily tested, so fingers crossed and let me know if you have problems. 
I'll leave this open for now.

**Comment by sdiemert** [comment]
@jenshweber Thanks for moving quickly on that! I can imagine there were many corner cases to work out! 

I have a task today where I can try this out... stay tuned

**Comment by sdiemert** [comment]
Found a bug! (or maybe its a feature...I can't tell).  Either way, when specifying a optional matches, the ordering of nodes/edges in the pattern matters. 

For example, the following (where `create-contract!` uses optional matching) result in Neo4j error: 

```clojure
(rule 'create-contract! ['name]
      :read (pattern (node 'p :label "Person" :asserts {:name "'&name'"})
                     (node 's :label "Person" :opt true)
                     (edge :label "parent_of" :src 's :tar 'p :opt true)
                     (node 'cp :label "Company"))
      :create (pattern (node 'c :label "Contract")
                       (edge :label "party" :src 'c :tar 'p)
                       (edge :label "party" :src 'c :tar 's)
                       (edge :label "owns" :src 'cp :tar 'c)))


(rule 'create-person! ['p]
  :create 
   (pattern 
    (node :label "Person" :asserts {:name "'&p'"})))

(rule 'create-company! ['c]
  :create 
   (pattern 
    (node :label "Company" :asserts {:name "'&c'"})))

(rule 'parent-of! ['p 'c]
 :read (pattern 
         (node 'f :label "Person" :asserts {:name "'&c'"})
         (node 'j :label "Person" :asserts {:name "'&p'"}))
 :create (pattern 
           (edge :label "parent_of" :src 'j :tar 'f )))

(clear!)

(create-person! "A")
(create-person! "B")
(parent-of! "A" "B")
(create-company! "ACME")
(create-contract! "A")
```


```
Exception thrown: java.lang.Exception (Transaction failed and rolled back. Error: [{:code "Neo.ClientError.Statement.SyntaxError", :message "MATCH cannot follow OPTIONAL MATCH (perhaps use a WITH clause between them) (line 1, column 101 (offset: 100))\r\n\" MATCH (p:Person {name:'A'}) OPTIONAL MATCH (s:Person) , (s)-[_w_twPBOsAd:parent_of]->(p) MATCH (cp:Company) WITH * WHERE 1=1 AND 1=1 RETURN ID(p) AS p, ID(s) AS s, ID(cp) AS cp, ID(_w_twPBOsAd) AS _w_twPBOsAd ORDER BY p, s, cp, _w_twPBOsAd\"\r\n ^"}])
raise-on-any-errors - clojurewerkz.neocons.rest.transaction - (transaction.clj:48)
raise-on-any-errors - clojurewerkz.neocons.rest.transaction - (transaction.clj:44)
make-request - clojurewerkz.neocons.rest.transaction - (transaction.clj:55)
make-request - clojurewerkz.neocons.rest.transaction - (transaction.clj:50)
real-execute - clojurewerkz.neocons.rest.transaction - (transaction.clj:65)
real-execute - clojurewerkz.neocons.rest.transaction - (transaction.clj:63)
execute - clojurewerkz.neocons.rest.transaction - (transaction.clj:105)
execute - clojurewerkz.neocons.rest.transaction - (transaction.clj:97)
dbquery - grape.core - (core.clj:137)
dbquery - grape.core - (core.clj:132)
match - grape.core - (core.clj:257)
match - grape.core - (core.clj:249)
run-transaction - grape.core - (core.clj:410)
run-transaction - grape.core - (core.clj:311)
run-transaction - grape.core - (core.clj:374)
run-transaction - grape.core - (core.clj:311)
transact-iter - grape.core - (core.clj:480)
transact-iter - grape.core - (core.clj:472)
attempt - grape.core - (core.clj:519)
attempt - grape.core - (core.clj:517)
invoke - (RestFn.java:408)
rule-os/fn - grape.core - (core.clj:701)
invoke - (RestFn.java:408)
eval18731 - user - (form-init5104076049147150963.clj:35)
eval18731 - user - (form-init5104076049147150963.clj:35)
eval - (Compiler.java:7177)
eval - (Compiler.java:7132)
eval - clojure.core - (core.clj:3214)
eval - clojure.core - (core.clj:3210)
repl/read-eval-print/fn - clojure.main - (main.clj:437)
repl/read-eval-print - clojure.main - (main.clj:437)
repl/fn - clojure.main - (main.clj:458)
repl - clojure.main - (main.clj:458)
repl - clojure.main - (main.clj:368)
invoke - (RestFn.java:1523)
evaluate - nrepl.middleware.interruptible-eval - (interruptible_eval.clj:79)
evaluate - nrepl.middleware.interruptible-eval - (interruptible_eval.clj:55)
interruptible-eval/fn/fn - nrepl.middleware.interruptible-eval - (interruptible_eval.clj:142)
run - (AFn.java:22)
session-exec/main-loop/fn - nrepl.middleware.session - (session.clj:171)
session-exec/main-loop - nrepl.middleware.session - (session.clj:170)
run - (AFn.java:22)
run - (Thread.java:834)
```


However, if I re-order the nodes/edges in the `create-contract!` rule things work as expected: 

```clojure
(rule 'create-contract! ['name]
      :read (pattern (node 'p :label "Person" :asserts {:name "'&name'"})
                     (node 'cp :label "Company")
                     (node 's :label "Person" :opt true)                     
                     (edge :label "parent_of" :src 's :tar 'p :opt true))
      :create (pattern (node 'c :label "Contract")
                       (edge :label "party" :src 'c :tar 'p)
                       (edge :label "party" :src 'c :tar 's)
                       (edge :label "owns" :src 'cp :tar 'c)))
```

It seems that the GRAPE is processing the nodes/edges in order and the optional nodes/edges must come at the end of a pattern. 

Is this the desired behaviour? If so, then we should update the tutorial to indicate node/edge ordering matters.

**Comment by sdiemert** [comment]
Also, there appears to be some latent print statements about transactions left in the code, probably from debugging... 

![image](https://user-images.githubusercontent.com/1484030/84536346-838da900-aca2-11ea-8878-1104be9d2a73.png)

**Comment by jenshweber** [comment]
@sdiemert Yes, sorry for the left over print statement. It's removed in 0.2.6 (just update your dependency)

BTW: I have now changed Grape, so debug info can be switched on / off dynamically.

(I am looking into the ordering issue)

**Comment by jenshweber** [comment]
@sdiemert I think I fixed the "optional ordering" bug you described. New version 0.2.7 pushed to Clojars

**Comment by sdiemert** [comment]
@jenshweber that's great. thanks! 

this has also fixed another bug I discovered where somehow optional elements where not being matched... or maybe it was a problem with my own rule. anyways, fixed now :-).

**Comment by jenshweber** [comment]
Excellent. 

FYI: if rules are behaving strangely, make sure you understand that I changed the "default semantics" of pattern matching too "homomorphic" matching rather than isomorphic matching.  So, two nodes in the pattern may match to the same node in the instance graph (unless you specify :iso). 

This speeds up things quite a bit - but your OLD rules may have to be revisited - and if you need isomorphism checks, you can just add the :iso tag.
