### ISSUE TITLE
Graceful Handling of No Matches

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#13]
When there are no matches, can `view` handle this more gracefully? Possibly just return `nil` (or `false`?) if there is nothing to display.

Every time I see an error I think I've done something wrong, which is not the case here...there are just no matches. 

![image](https://user-images.githubusercontent.com/1484030/84441603-f8a0a600-abf0-11ea-9f9f-8a8230310e30.png)

Could it be that I am using the threading operation incorrectly?

**Comment by jenshweber** [comment]
Yes that should be a simple fix.

**Comment by jenshweber** [comment]
The new version of Grape (GrapeVine) no longer has that issue. I am closing this one.
