### ISSUE TITLE
Assign without creating other elements

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#14]
Right now it appears that the `(assign ...)` operator requires that it be incorporated into a pattern that also creates other nodes/edges. 

For example, 

```clojure
(rule 'create-person! ['p]
  :create 
   (pattern 
    (node :label "Person" :asserts {:name "'&p'"})))

(rule 'change-name! ['x 'y]
      :read (pattern (node 'n :label "Person" :asserts {:name "'&x'"}))
      :create (pattern 
               (assign "n.name='&y'")))

(clear!)

(create-person! "Simon")
(-> any? matches view)

(change-name! "Simon" "Bob")
(-> any? matches view)
```

Does not have the desired effect. It fails to do the assignment of `Simon -> Bob`.

However, if I add a `DONT_CARE` node to the create pattern then it works as desired. 

```clojure
(rule 'create-person! ['p]
  :create 
   (pattern 
    (node :label "Person" :asserts {:name "'&p'"})))

(rule 'change-name! ['x 'y]
      :read (pattern (node 'n :label "Person" :asserts {:name "'&x'"}))
      :create (pattern 
               (node :label "DONT_CARE")
               (assign "n.name='&y'")))
```

**Comment by sdiemert** [comment]
This can be mitigated for now using the `:merge true` option on the DONT_CARE nodes (so you only ever have one of these... but it still isn't ideal in my view.

**Comment by jenshweber** [comment]
I am going to revisit this part in context of the next major release of Grape.

**Comment by jenshweber** [comment]
Since the new version of Grape (GrapeVine) no longer has assignments (since it is functional), I am closing this issue.
