### ISSUE TITLE
Docker Quickstart

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#23]
Attempting to start the Neo4j container using (as shown in the README)

> docker run --name neo4j -p 7474:7474 -p 7687:7687 --net grapenet -d -v $HOME/neo4j/data:/data -v $HOME/neo4j/logs:/logs -v $HOME/neo4j/import:/var/lib/neo4j/import -v $HOME/neo4j/plugins:/plugins -e NEO4JLABS_PLUGINS=\[\"apoc\"\] -e NEO4J_apoc_export_file_enabled=true -e NEO4J_AUTH=none -e NEO4J_apoc_import_file_use__neo4j__config=true -e NEO4J_apoc_import_file_enabled=true -e NEO4J_cypher_lenient__create__relationship=true -e NEO4JLABS_PLUGINS=\[\"apoc\"\] neo4j

Fails to start the Docker container. The container's log contains: 

> NEO4JLABS_PLUGINS has been renamed to NEO4J_PLUGINS since Neo4j 5.0.0.
The old name will still work, but is likely to be deprecated in future releases.
Plugin at '/plugins/apoc.jar' is not readable
Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /plugins/apoc.jar

Using 2022 M1 Macbook Pro (not sure if that matters).

**Comment by jenshweber** [comment]
I think this one has been resolved now
