### ISSUE TITLE
Using rule arguments in "assign" 

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#3]
Hi @jenshweber,

I am trying to use a rule argument within an assign expression: 

```
(rule 'add_timeframe! ['duration 'frame 'freq]
      {:read (pattern
               (node 'i1 {:asserts {:kind "'Instruction'"}})
               (NAC
                 (node 'tf {:asserts {:kind "'TimeFrame'"}})
                 (edge 'e {:label "timeframe" :src 'i1 :tar 'tf})
               )
             )
       :create (pattern
                 (node 'tf {:asserts {:frame "'&frame'" :frequency "'&freq'" :kind "'TimeFrame'"}})
                 (edge 'e {:label "timeframe" :src 'i1 :tar 'tf})
                 (assign "i1.duration='&duration'")
               )
      }
)
```

Invoking the rule: 

```
(create_rx! "Aspirin")
(add_instruction! "take")
(add_timeframe! 10 "DAY" "2")
```

I would like to be able to take the value of duration and assign it to an existing node's duration attribute. This seems like it should work. However it gives me a graph that looks like the one in the following image: [https://www.dropbox.com/s/9ib9k5dq20yup75/Screenshot%202016-05-28%2015.31.33.png?dl=0](https://www.dropbox.com/s/9ib9k5dq20yup75/Screenshot%202016-05-28%2015.31.33.png?dl=0)  . Notice that the duration attribute is set to `&duration`, not 10 as I had hoped. 

Any thoughts on this? Perhaps i am overlooking something simple.

**Comment by jenshweber** [comment]
Hi Simon,
I implemented a fix for this. One comment. If the node property _duration_ is a number, you don't need the quotes in the assignment.  In other words `(assign "i1.duration=&duration")` is fine for numbers. You need the quotes only for strings.
Jens
