### ISSUE TITLE
FEATURE REQUEST: Modules

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#5]
Hey @jenshweber,

I have been using Grape to build a GTS for my thesis project. You can check it out: [https://github.com/sdiemert/medication-model](https://github.com/sdiemert/medication-model), I think I invited you, so you should be able to view the project. 

I think it would be nice to have some form of "modularity" for GT systems in Grape. I have found myself wanting to re-use rules in several GTSs that I have defined and I have been copying and pasting rules to achieve the desired effect. This seems to be an unsustainable practice. 

Do you know of an easy way to do this? 

My current solution is to define the function that generate the Hashes grape's `(rule 'name Hash)` function consumes and call during rule definition. Check this out in: 
- [https://github.com/sdiemert/medication-model/blob/master/src/app/rxCoreRules.clj](https://github.com/sdiemert/medication-model/blob/master/src/app/rxCoreRules.clj)
- [https://github.com/sdiemert/medication-model/blob/master/src/app/rxCore.clj](https://github.com/sdiemert/medication-model/blob/master/src/app/rxCore.clj)

However, there are a few things that make this non-ideal: 
- Still have to re-create each rule for the current GTS
- Parameter names to the rule must match the parameter names to the details of the rule (I think?)

Thoughts?

Perhaps there is something interesting here from a theoretical point of view?  Having GGs as an extension of a programming language makes me want to apply standard modularization patterns to them.

**Comment by jenshweber** [comment]
Modularity is now supported using the normal Clojure packaging (namespace) system. I am closing this request. Let me know if this is not meeting your requirements.
