### ISSUE TITLE
Updating Node Attributes

### ISSUE THREAD

**Issue by sdiemert** [jenshweber/grape#9]
Are node attributes considered immutable in GRAPE? Once an attribute is set, is it possible to modify the attribute later using another rule? 

For example, suppose have a rule: 

```clojure
(rule 'add_person ['n] 
      {:create 
       (pattern
       (node 'p {:label "Person" :asserts {:name "'&n'"}}))})
```

What if I wanted to change the name of a person? Can I accomplish this with the `:merged` operator? It does not seem so, my attempt is: 

```clojure
(rule 'change_name ['from 'to]
      {:read
       (pattern 
        (node 'p1 {:label "Person" :asserts {:name "'&from'"}}))
       :create
       (pattern
        (node 'p2 {:label "Person" :asserts {:name "'&to'"} :merge true}))
       })
```

If nodes attributes are intended to be immutable, then the obvious solution is to make a child node of a Person called labelled "name" and then add/delete those nodes to modify values directly.

@jenshweber - thoughts on this?

**Comment by jenshweber** [comment]
@sdiemert No, attributes are not immutable. They can be re-assigned using "assign". Check out the Ferryman example in the tutorial.
http://viewer.gorilla-repl.org/view.html?source=github&user=jenshweber&repo=grape&path=tutorial.clj

**Comment by sdiemert** [comment]
Ah, yes! I hadn't gotten that far in the tutorial yet. Its coming back to me now... thank you :-).
